#spring:
#  datasource:
#    url: abcdefg
#    username: abcdefg
#    password: abcdefg

# ??? git? ??? ? ???? ?? ????? ??? ?? ??
# run configurations - environment variables ??
# SPRING_DATASOURCE_URL=???user=??&password=????
# ??
# ????? export SPRING_DATASOURCE_URL=...